#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

set -e

echo ''

info() {
	printf " [ \033[00;34m..\033[0m ] $1"
}

user() {
	printf "\r [ \033[0;33m?\033[0m ] $1"
}

success() {
	printf "\r\033[2k [033[00;32mOK\033[0m ] $1\n"
}

fail() {
	printf "\r\033[2k [033[0;31mFAIL[033[0m] $1\n"
}

info 'setup git config'
user ' - What is your github author name?'
#success 'gitconfig'